In [1]:
import torch
import numpy as np

In [2]:
import sys

print(sys.path)

['/Users/dlq/Pytorch_record', '/Users/dlq/Pytorch_record', '', '/opt/homebrew/Cellar/pyside@2/5.15.2/lib/python3.9/site-packages', '/Users/dlq/miniforge3/envs/pytorch/lib/python39.zip', '/Users/dlq/miniforge3/envs/pytorch/lib/python3.9', '/Users/dlq/miniforge3/envs/pytorch/lib/python3.9/lib-dynload', '/Users/dlq/miniforge3/envs/pytorch/lib/python3.9/site-packages', '/Users/dlq/miniforge3/envs/pytorch/lib/python3.9/site-packages/IPython/extensions', '/Users/dlq/.ipython']


## 1. 初始化一个张量

### 1.1 直接从列表数据生成
data: a list

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


### 1.2 使用Numpy数组创建

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])


### 1.3 使用另一个已有张量

In [10]:
x_ones = torch.ones_like(x_data)
print(f'x_ones:\n{x_ones}')
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'x_rand:\n{x_rand}')

x_ones:
tensor([[1, 1],
        [1, 1]])
x_rand:
tensor([[0.9053, 0.2512],
        [0.8981, 0.7536]])


### 1.4 使用固定值或随机值
shape是张量维度的元组，它决定了输出张量的维度。

In [4]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'rand_tesnor: \n {rand_tensor} \n')
print(f'ones_tensor: \n {ones_tensor} \n')
print(f'zeros_tensor: \n {zeros_tensor} \n')

rand_tesnor: 
 tensor([[0.3155, 0.1040, 0.0080],
        [0.0521, 0.7990, 0.7086]]) 

ones_tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros_tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 2. Tensor的属性
张量的属性用于描述张量本身的尺寸、数据类型以及变量储存的位置。

In [5]:
tensor = torch.rand(3, 4)

print('Shape of tensor:', tensor.shape)
print('Datatype of tensor:', tensor.dtype)
print('device of tensor:', tensor.device)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
device of tensor: cpu


## 3. 对Tensor的操作
对张量的操作超过100种，包括算术、线性代数、矩阵操作（转置、索引、切片），这些操作既可以在CPU上完成，也可以在GPU上完成，在GPU上进行运算的速度更快一些。
一般而言，张量是在CPU上创建的，我们需要使用.to命令来将张量移动到GPU中。但是跨设备进行大尺度张量的复制操作是花费很多时间和内存的。

In [ ]:
# we move our tensors to the GPU fi available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

对张量进行操作（类似Numpy）

In [3]:
tensor = torch.ones(4, 4)
print('First row:', tensor[0])
print('First column:', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


张量级联：可以使用torch.cat来将一系列张量沿着指定的维度进行级联，实际上torch.stack也可以用来对张量进行拼接，但是二者的关键区别在于：返回的Tensor的维数是否会发生改变。

In [10]:
a = torch.ones(2, 3)
b = torch.ones(2, 3)
cat = torch.cat((a, b), dim=1) # dim指定拼接维度，默认值为0
stack = torch.stack((a, b), dim=1)
print('shape of tensor with torch.cat:', cat.shape)
print('shape of tensor with torch.stack:', stack.shape)

shape of tensor with torch.cat: torch.Size([2, 6])
shape of tensor with torch.stack: torch.Size([2, 2, 3])


矩阵运算：以矩阵乘法和点乘为例

In [11]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0

# 这里将要计算两个张量之间的矩阵乘法，y1,y2,y3具有相同的值
y1 = tensor @ tensor.T # .T表示转置
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print('y1:', y1)
print('y2:', y2)
print('y3:', y3)

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [13]:
tensor = torch.rand(4, 4)

# 这里将要计算两个张量之间的点乘运算，z1,z2,z3具有相同的值
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print('z1:', z1)
print('z2:', z2)
print('z3:', z3)

z1: tensor([[0.9925, 0.0130, 0.7903, 0.1408],
        [0.1539, 0.1473, 0.4970, 0.0156],
        [0.3221, 0.3825, 0.1823, 0.5702],
        [0.8966, 0.1325, 0.4991, 0.0054]])
z2: tensor([[0.9925, 0.0130, 0.7903, 0.1408],
        [0.1539, 0.1473, 0.4970, 0.0156],
        [0.3221, 0.3825, 0.1823, 0.5702],
        [0.8966, 0.1325, 0.4991, 0.0054]])
z3: tensor([[0.9925, 0.0130, 0.7903, 0.1408],
        [0.1539, 0.1473, 0.4970, 0.0156],
        [0.3221, 0.3825, 0.1823, 0.5702],
        [0.8966, 0.1325, 0.4991, 0.0054]])


单元素张量：如果我们有一个单元素的张量，那么我们可以用item()将其转化为python中的纯数值

In [16]:
tensor = torch.ones(4, 4)
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(16.) <class 'torch.Tensor'>
16.0 <class 'float'>


就地操作：将结果存储到操作数中的操作被就地调用。这些操作会带有_符号。

In [17]:
tensor = torch.ones(4, 4)
print(tensor)

tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


## 4. 与Numpy之间的联系
CPU中的张量可以和Numpy数组共享底层的存储地址，对其中一个进行修改将会同时修改另一个。
### 4.1 张量 ——> Numpy

In [27]:
t = torch.ones(5)
print('t:', t)

n = t.numpy()
print('n:', n)

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [28]:
# 修改张量中的元素，查看Numpy数组是否会跟着变动
t.add_(1)
print('t:', t)
print('n:', n)

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 4.2 Numpy ——> Tensor

In [23]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print('t:', t)
print('n:', n)

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
