In [1]:
import torch

In [19]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)

y.backward(retain_graph=True)
print(w.grad)
# w.grad.zero_()

y.backward()
print(w.grad)

tensor([5.])
tensor([5.])


In [16]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)

a  = torch.add(w, x)
b = torch.add(w, 1)
y0 = torch.mul(a, b)
y1 = torch.add(a, b)

loss = torch.cat([y0, y1], dim=0)
print('shape of loss:{}'.format(loss.shape))
grad_tensors = torch.tensor([1., 2.])

loss.backward(gradient=grad_tensors)
print(w.grad)
print(x.grad)

shape of loss:torch.Size([2])
tensor([9.])
tensor([4.])


In [17]:
x = torch.tensor([3.], requires_grad=True)
y = pow(x, 2)
grad_1 = torch.autograd.grad(y, x, create_graph=True)
print(grad_1)
grad_2 = torch.autograd.grad(grad_1[0], x)
print(grad_2) 

(tensor([6.], grad_fn=<MulBackward0>),)
(tensor([2.]),)


In [18]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
# 进行 4 次反向传播求导，每次最后都没有清零
for i in range(4):
    a = torch.add(w, x)
    b = torch.add(w, 1)
    y = torch.mul(a, b)
    y.backward()
    print(w.grad)

tensor([5.])
tensor([10.])
tensor([15.])
tensor([20.])


In [20]:
print('非inplace操作')
t = torch.ones(1)
print(id(t), t)
t = t + torch.ones(1)
print(id(t), t)

print('inplace操作')
a = torch.ones(1)
print(id(a), a)
a += torch.ones(1)
print(id(a), a)

非inplace操作
3082445421768 tensor([1.])
3082445372616 tensor([2.])
inplace操作
3082445408120 tensor([1.])
3082445408120 tensor([2.])
