In [1]:
import torch
import numpy as np

In [3]:
arr = np.ones((3, 3))
print("ndarray的数据类型：", arr.dtype)
# 创建存放在GPU的数据
# t = torch.tensor(arr, device='cuda')
# 创建存放在CPU的数据
t = torch.tensor(arr)
print(t)

ndarray的数据类型： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
t = torch.from_numpy(arr)

# 修改array, tensor也会被修改
print('\n修改arr')
arr[0, 0] = 0
print('numpy array:', arr)
print('tensor:', t)

# 修改tensor，arr也会被修改
# print('\n修改tensor')
# t[0, 0] = -1
# print('numpy array:', arr)
# print('tensor:', t)


修改arr
numpy array: [[0 2 3]
 [4 5 6]]
tensor: tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [5]:
out_t = torch.tensor([1])
print('original out_t:', out_t)
# 这里指定了out
t = torch.zeros((3, 3), out=out_t)
print(t, '\n', out_t)
# id是取内存地址，最终t和out_t是同一个内存地址
print(id(t), id(out_t), id(t)==id(out_t))

original out_t: tensor([1])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
1642408016296 1642408016296 True


In [10]:
t = torch.full((3, 3), 5.)
print(t)
t_like = torch.full_like(t, 4)
print(t_like)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [12]:
t = torch.arange(5)
print(t)
t = torch.arange(1, 7, 2)
print(t)

tensor([0, 1, 2, 3, 4])
tensor([1, 3, 5])


In [17]:
t =torch.linspace(2, 10, 6)
print(t)
print(t.dtype)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])
torch.float32


In [23]:
t =torch.logspace(1, 2, 10)
print(t)
print(t.dtype)

tensor([ 10.0000,  12.9155,  16.6810,  21.5443,  27.8256,  35.9381,  46.4159,
         59.9484,  77.4264, 100.0000])
torch.float32


In [25]:
t = torch.eye(3)
print(t)
t = torch.eye(3, 4)
print(t) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [32]:
t = torch.normal(0., 1., size=(4,))
print(t)

tensor([ 0.0971, -1.4530,  0.7696,  0.4342])


In [38]:
mean = 0
std = torch.arange(1, 5, dtype=torch.float)
t = torch.normal(mean, std)
print(t)

tensor([-1.1284, -0.4638, -7.4014,  1.6936])


In [40]:
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t = torch.normal(mean, std)
print(t)

tensor([1.2607, 2.3880, 3.4902, 4.3429])


In [3]:
mean = torch.ones(100, 2)
bias = 1
# t = torch.normal(1.7*mean, 1) + 1
t = mean + 1
print(t)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2

In [57]:
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}, std:{}".format(mean, std))
print(t_normal)

mean:tensor([1., 2., 3., 4.]), std:tensor([1., 2., 3., 4.])
tensor([0.8217, 1.8432, 2.6116, 2.5892])


In [60]:
input = torch.tensor([0.8, 0.2])
t_bernoul = torch.bernoulli(input)
print(t_bernoul)

tensor([1., 0.])
